### ISSUE TITLE
Increased failure rate on scene load?

### ISSUE THREAD

**Issue by aw1621107** [jwvanderbeck/TestFlight#64]
I've noticed that TF-supported engines seem to have a markedly higher failure rate upon loading the vessel. At this point this mostly happens for in-atmosphere burns, when I hop to the space center to accept the next sounding rocket contract then back to the rocket, or if I quickload after something bad happens (admittedly, saving in-atmosphere during a burn may not be the best idea...). Not sure if this is observation bias, but it seems to happen frequently even for relatively reliable engines like the XLR11.

Might be clearer for engine clusters. Had a 9-Aerobee cluster sometime back before I got FASA figured out, and upon quickloading into a mid-atmosphere burn 4+ engines would always immediately fail, until I gave up and scrapped the launch.

**Comment by jwvanderbeck** [comment]
At first thought what is most likely happening is that the reliability calc which is usually done for MET and MET+1, is probably instead happening between something like 0 and MET which if MET is high would result in a pretty drastic survival chance.

I need to do some testing.

**Comment by aw94** [comment]
Just realized; perhaps that can also explain why engines seem to get astronomically high amounts of data upon scene load too?

**Comment by jwvanderbeck** [comment]
No the astronomically large amounts of data (which isn't actually getting
recorded) is due to somewhere along the chain of things an exception is
being thrown

- John Vanderbeck
- http://www.johnvanderbeck.com

**Comment by aw94** [comment]
Ah, ok. That explains a lot.

**Comment by jwvanderbeck** [comment]
Ok I can confirm that when loading an existing mission, things are getting all messed up.  So for now i'd suggest not quick saving/loading :)

**Comment by aw94** [comment]
:( Yay hard mode?

**Comment by jwvanderbeck** [comment]
Its how I play.  You can't redo a launch in real life!

**Comment by aw94** [comment]
Very true... Guess RO/RP-0 is just too real for me :P

**Comment by jwvanderbeck** [comment]
In any case I see what the issue is but its not going to be easy to fix.

**Comment by jwvanderbeck** [comment]
Mostly fixed in 1.2.2.  There are some further complications in maintaining things like ignition state, since apparently KSP completely re initializes everything and starts the engines out not-ignited again when you load.  That is going to take further work and a lot of refactoring to fix, but for now at least the failure rate won't jump through the roof anymore.

**Comment by aw94** [comment]
Does that mean that ignition failures might still happen, but everything else is ok?

**Comment by jwvanderbeck** [comment]
It means a new ignition failure check happens, and that the engine is
treated as just started up so it will have that normal 5 second period of
increased failure rate as per the engine configs.

- John Vanderbeck
- http://www.johnvanderbeck.com

**Comment by aw94** [comment]
Ah, ok. Thanks!

**Comment by jwvanderbeck** [comment]
Hopefully once I finish the refactoring I can avoid these side effects.
But for now at least you don't have that incorrectly massive high failure
rate when loading, which basically gave the engine a 0% survival rate :)

- John Vanderbeck
- http://www.johnvanderbeck.com

**Comment by jwvanderbeck** [comment]
This issue should be resolved in 1.3 due to the refactoring.
